/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BatchExportDiog: typeof import('./src/components/content/test/batchExportDiog.vue')['default']
    Cascader: typeof import('./src/components/common/cascader.vue')['default']
    CreateTestDrawer: typeof import('./src/components/content/test/createTestDrawer.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    HeadeTitle: typeof import('./src/components/common/headeTitle.vue')['default']
    MyEditor: typeof import('./src/components/common/MyEditor.vue')['default']
    PublicDialog: typeof import('./src/components/common/publicDialog.vue')['default']
    QuertionDialog: typeof import('./src/components/content/test/quertionDialog.vue')['default']
    QuestionsList: typeof import('./src/components/content/test/questionsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentText: typeof import('./src/components/content/test/studentText.vue')['default']
    TableConfig: typeof import('./src/components/common/TableConfig.vue')['default']
    TestDrawer: typeof import('./src/components/content/test/testDrawer.vue')['default']
    TestpaperDialog: typeof import('./src/components/content/test/testpaperDialog.vue')['default']
  }
}
